import type { DiagnosisOutput } from "@/harness/guardrails/schema";

export function renderDiagnosisMd(
  diagnosis: DiagnosisOutput,
  meta?: { requestId?: string; vehicle?: string },
): string {
  const lines: string[] = [
    "# Vroom Vroom Diagnosis Report",
    "",
    meta?.requestId ? `**Request ID:** ${meta.requestId}` : "",
    meta?.vehicle ? `**Vehicle:** ${meta.vehicle}` : "",
    meta?.requestId || meta?.vehicle ? "" : "",
    "## Summary",
    diagnosis.summary,
    "",
    "## Most Likely Cause",
    `**${diagnosis.mostLikelyCause}**`,
    "",
    `**Confidence:** ${diagnosis.confidence}`,
    "",
    "## Diagnostic Steps",
  ];

  for (const step of diagnosis.diagnosticSteps) {
    lines.push(`### Step ${step.step}`);
    lines.push(step.action);
    lines.push("");
    if (step.toolsNeeded.length > 0) {
      lines.push(`**Tools needed:** ${step.toolsNeeded.join(", ")}`);
    }
    if (step.safetyNotes && step.safetyNotes.length > 0) {
      lines.push("**Safety notes:**");
      for (const note of step.safetyNotes) {
        lines.push(`- ${note}`);
      }
    }
    lines.push("");
  }

  lines.push("## When to Seek a Professional");
  for (const item of diagnosis.whenToSeekPro) {
    lines.push(`- ${item}`);
  }
  lines.push("");

  if (diagnosis.sources.length > 0) {
    lines.push("## Sources");
    for (const source of diagnosis.sources) {
      lines.push(`- [${source.title}](${source.url})`);
    }
    lines.push("");
  }

  lines.push("## Disclaimer");
  lines.push(diagnosis.disclaimer);
  lines.push("");
  lines.push("---");
  lines.push("*Generated by Vroom Vroom — traditional ICE vehicles only. Not a substitute for professional diagnosis.*");

  return lines.filter((line, i, arr) => !(line === "" && arr[i + 1] === "")).join("\n");
}
